; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define ToolName "VRChat ToolBox"
#define ToolVersion "9.7.2"
#define ToolPublisher "Boots"
#define ToolExeName "ToolBox.exe"

[Setup]
; Unique App ID for VRChat ToolBox
AppId={{5D0BFA9D-351E-47C1-87F4-2B4D7E2D1234}
AppName={#ToolName}
AppVersion={#ToolVersion}
AppPublisher={#ToolPublisher}
DefaultDirName={autopf}\VRChat-ToolBox
DefaultGroupName={#ToolName}
AllowNoIcons=yes
LicenseFile=LICENSE
; Output directory and name for the compiled installer
OutputDir=.
OutputBaseFilename=VRChat-ToolBox-Setup
SetupIconFile=Images\Boot's-ToolBox.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Standalone executable compiled by PyInstaller
Source: "dist\ToolBox.exe"; DestDir: "{app}"; Flags: ignoreversion
; Entire VRChat-Tools subdirectory (portable tools)
Source: "VRChat-Tools\*"; DestDir: "{app}\VRChat-Tools"; Flags: ignoreversion recursesubdirs createallsubdirs
; Images and assets
Source: "Images\*"; DestDir: "{app}\Images"; Flags: ignoreversion recursesubdirs createallsubdirs
; Root license and readme files
Source: "LICENSE"; DestDir: "{app}"; Flags: ignoreversion
Source: "README.md"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\{#ToolName}"; Filename: "{app}\{#ToolExeName}"
Name: "{group}\{cm:UninstallProgram,{#ToolName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#ToolName}"; Filename: "{app}\{#ToolExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#ToolExeName}"; Description: "{cm:LaunchProgram,{#StringChange(ToolName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
